# Generated by Django 6.0.2 on 2026-03-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WacStaff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
